apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-vgr-backend
  labels:
    app: prometheus
spec:
  endpoints:
  - interval: 10s
    port: http
    path: /actuator/prometheus
  selector:
    matchLabels:
      app: vgr-backend