{
 "title": "vgr-backend",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Success Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{container=\"vgr-backend\", outcome=\"SUCCESS\"}[5m])) / sum(increase(http_server_requests_seconds_count{container=\"vgr-backend\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum[1m]) / rate(http_server_requests_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up {job=\"vgr-backend\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "process_cpu_usage * 100" }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes {area=\"heap\"}) / sum(jvm_memory_max_bytes {area=\"heap\"})"
    }
   ]
  },
  {
   "title": "JVM Stack Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes {area=\"nonheap\"}) / sum(jvm_memory_max_bytes {area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Traffic Distribution",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count[5m])) by (pod) / scalar(sum(increase(http_server_requests_seconds_count[5m]))) * 100"
    }
   ]
  }
 ]
}