apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2021-05-25T20:38:06Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: prometheus
    operator.prometheus.io/name: kube-prometheus-stack-prometheus
    operator.prometheus.io/shard: "0"
    prometheus: kube-prometheus-stack-prometheus
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:operator.prometheus.io/name: {}
          f:operator.prometheus.io/shard: {}
          f:prometheus: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:storageClassName: {}
        f:volumeMode: {}
      f:status:
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-25T20:38:06Z"
  name: prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0
  namespace: default
  resourceVersion: "49250"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0
  uid: ce4f7f0c-1676-4e3b-b366-bf6b0f9f3f9e
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: standard
  volumeMode: Filesystem