---
- name: Export Jenkins Password
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Remove file 
      command:
        cmd: sudo rm /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/jp    
    
    - name: Writing to file 
      command:
        cmd: echo "{{ hostvars['vgrbackend'].ADMIN_PASSWORD.stdout }}" >> /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/jp