---
- name: Export Jenkins Password
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove file 
      command:
        cmd: sudo rm /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/jp    
    
    - name: Writing to file 
      shell: echo -n "{{ hostvars[groups['vgrbackend'][0]].ADMIN_PASSWORD.stdout }}" >> /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/jp
      changed_when: false