---
# - name: Grab Jenkins admin password
#   hosts: vgrbackend
#   gather_facts: false
#   become: true
#   tasks:
#     - name: Get init password Jenkins
#       shell: cat /var/lib/jenkins/secrets/initialAdminPassword
#       changed_when: false
#       register: ADMIN_PASSWORD

#     - name: Testing admin password
#       debug:
#         var: ADMIN_PASSWORD

- name: Export Jenkins Password
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove file 
      command:
        cmd: sudo rm /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/jp    
    
    - name: Writing to file 
      shell: echo -n "{{ hostvars[groups['vgrbackend'][0]].ADMIN_PASSWORD.stdout }}" >> /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/jp
      changed_when: false