---
- name: Install Jenkins
  hosts: vgrbackend
  gather_facts: false
  become: true
  tasks: 
    - name: Download Jenkins Repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
 
    - name: Import Jenkins Key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
 
    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Disable CSRF
      command: 
        cmd: sudo bash -c "echo \'JAVA_ARGS=\"$JAVA_ARGS -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true\"\' >> /etc/sysconfig/jenkins"
 
    - name: Start & Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true
 
    - name: Sleep for 30 seconds and continue with play
      wait_for: timeout=30
 
    - name: Get init password Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: ADMIN_PASSWORD
 
    - name: Print init password Jenkins
      debug:
        var: ADMIN_PASSWORD.stdout