---
- name: Install Jenkins Plugins
  hosts: vgrbackend
  gather_facts: false
  become: true
  tasks:    
    - name: Pause a minute to let Jenkins start
      pause:
        minutes: 1

    - name: Install git plugin
      community.general.jenkins_plugin:
        name: git
        url: "{{ hostvars['localhost'].DNS.stdout }}"
        url_username: admin
        url_password: "{{ADMIN_PASSWORD.stdout}}"

    - name: Install github plugin
      community.general.jenkins_plugin:
        name: github
        url: "{{ hostvars['localhost'].DNS.stdout }}"
        url_username: admin
        url_password: "{{ADMIN_PASSWORD.stdout}}"

    - name: Install octoperf plugin
      community.general.jenkins_plugin:
        name: octoperf
        url: "{{ hostvars['localhost'].DNS.stdout }}"
        url_username: admin
        url_password: "{{ADMIN_PASSWORD.stdout}}"

    - name: Install generic webhook trigger plugin
      community.general.jenkins_plugin:
        name: generic-webhook-trigger
        url: "{{ hostvars['localhost'].DNS.stdout }}"
        url_username: admin
        url_password: "{{ADMIN_PASSWORD.stdout}}"

    - name: Install docker plugin for Jenkins
      community.general.jenkins_plugin:
        name: docker-plugin
        url: "{{ hostvars['localhost'].DNS.stdout }}"
        url_username: admin
        url_password: "{{ADMIN_PASSWORD.stdout}}"

    - name: Install email-extension plugin
      community.general.jenkins_plugin:
        name: email-ext
        url: "{{ hostvars['localhost'].DNS.stdout }}"
        url_username: admin
        url_password: "{{ADMIN_PASSWORD.stdout}}"

    - name: Install performance report plugin
      community.general.jenkins_plugin:
        name: performance
        url: "{{ hostvars['localhost'].DNS.stdout }}"
        url_username: admin
        url_password: "{{ADMIN_PASSWORD.stdout}}"

    - name: Install pipeline plugin
      community.general.jenkins_plugin:
        name: workflow-aggregator
        url: "{{ hostvars['localhost'].DNS.stdout }}"
        url_username: admin
        url_password: "{{ADMIN_PASSWORD.stdout}}"      
    
    - name: Restart Jenkins so that plugins can integrate
      systemd:
        name: jenkins
        state: restarted
        enabled: true

    - name: Pause a minute so that Jenkins can restart
      pause:
        minutes: 1