---
# - name: Grab Variables
#   hosts: localhost
#   gather_facts: false
#   become: true
#   tasks:

- name: Developing
  hosts: vgrbackend
  gather_facts: false
  become: true
  tasks:
    - name: vgr-backend Load Test
      community.general.jenkins_job:
        config: "{{ lookup('file', '/home/erniek86/jenkins/vgr-backend Load Test/config.xml') }}"
        name: vgr-backend Load Test
        password: "{{ADMIN_PASSWORD.stdout}}"
        url: "{{ hostvars['localhost'].DNS.stdout }}"
        user: admin

    # - name: Add cloud for docker
    #   community.general.jenkins_script:
    #     user: admin
    #     password: "{{ADMIN_PASSWORD.stdout}}"
    #     script: |
    #       import hudson.slaves.*

    #       def javaHome = new EnvironmentVariablesNodeProperty(
    #         new EnvironmentVariablesNodeProperty.Entry('JAVA_HOME', '/usr/lib/jvm/java-7-oracle-amd64'))

    #       hudson.model.Hudson.instance.slaves.each { it.nodeProperties.add(javaHome) }

    # - name: Restart Jenkins
    #   systemd:
    #     name: jenkins
    #     state: restarted
    #     enabled: true
    
    # - name: Delete old git tool path
    #   command:
    #     cmd: sudo rm /var/lib/jenkins/hudson.plugins.git.GitTool.xml
    
    # - name: Configure git tool path
    #   command:
    #     cmd: sudo bash -c "echo \"{{ hostvars['localhost'].GIT_TOOL_CONFIG.stdout }}\" >> /var/lib/jenkins/hudson.plugins.git.GitTool.xml"
    
    # - name: Delete old docker tool path
    #   command:
    #     cmd: sudo rm /var/lib/jenkins/org.jenkinsci.plugins.docker.commons.tools.DockerTool.xml
    
    # - name: Configure docker tool path
    #   command:
    #     cmd: sudo bash -c "echo \"{{ hostvars['localhost'].DOCKER_TOOL_CONFIG.stdout }}\" >> /var/lib/jenkins/org.jenkinsci.plugins.docker.commons.tools.DockerTool.xml"