---
- name: Create Jenkins Job
  hosts: vgrbackend
  gather_facts: false
  become: true
  tasks:
    
    - name: Create a jenkins job using basic authentication
      community.general.jenkins_job:
        config: "{{ lookup('file', '/home/erniek86/jenkins/vgr-backend CICD/config.xml') }}"
        name: vgr-backend CICD
        password: "{{ADMIN_PASSWORD.stdout}}"
        url: "{{ hostvars['localhost'].DNS.stdout }}"
        user: admin