---
- name: Grab Variables
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Grab DNS
      shell: cat /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/new_dns
      changed_when: false
      register: DNS

    - name: Grab Github Token
      shell: cat /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/ght
      changed_when: false
      register: GITHUB_ACCESS_TOKEN

    - name: Add Github Webhook
      command:
        cmd: 'curl -X POST -H \"Accept: application/vnd.github.v3+json\" -H \"Authorization: Bearer $GITHUB_ACCESS_TOKEN\" https://api.github.com/repos/ernestk86/vgr-backend/actions/workflows/build.yml/dispatches -d \'{\"ref\":\"main\"}\''

    - name: Grab Dockerhub Username
      shell: cat /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/dhuser
      changed_when: false
      register: DOCKERHUB_USERNAME
    
    - name: Grab Dockerhub Password
      shell: cat /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/dhpass
      changed_when: false
      register: DOCKERHUB_PASSWORD
    
    - name: Grab Octoperf Username
      shell: cat /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/opuser
      changed_when: false
      register: OCTOPERF_USERNAME
    
    - name: Grab Octoperf Password
      shell: cat /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/oppass
      changed_when: false
      register: OCTOPERF_PASSWORD
    
    - name: Grab smtp Password
      shell: cat /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/smtpPass
      changed_when: false
      register: SMTP_PASSWORD

    - name: Grab docker config
      shell: cat /mnt/c/users/ernes/desktop/ernie_work/vgr-backend/forbidden/org.jenkinsci.plugins.docker.commons.tools.DockerTool.xml
      changed_when: false
      register: DOCKER_TOOL_CONFIG

- name: Setup proper tools
  hosts: vgrbackend
  gather_facts: false
  become: true
  tasks:
    - name: Install Docker
      yum:
        name: docker

    - name: Start & Enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Install Git
      yum:
        name: git

    - name: Install Pip2
      yum:
        name: pip
    
    - name: Ensure python-jenkins is installed
      pip:
        executable: /usr/bin/pip
        name: python-jenkins

- name: Unlock Docker for Jenkins access
  hosts: vgrbackend
  gather_facts: false
  become: true
  tasks:
    - name: Unlock Docker.sock
      command:
        cmd: sudo chmod 666 /var/run/docker.sock