name: DOCKER
on:
  workflow_dispatch:
jobs:
  Docker_Build_Push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vgr-backend-canary:latest
  Handoff_to_Jenkins_Canary:
    runs-on: ubuntu-latest
    steps:
      - name: Hand off to Jenkins
        run: |
          curl -X POST http://${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_TOKEN }}@ec2-3-133-100-143.us-east-2.compute.amazonaws.com:9090/job/vgr-backend%20Canary%20and%20Load%20Test/build?token=canary
